await Bun.build({
  entrypoints: ['./src/main.ts'],
  format: 'esm',
  outdir: './out',
  // sourcemap: 'linked',
  sourcemap: 'none',
  target: 'node',
  external: [
    '@apollo/server',
    '@apollo/subgraph',
    '@grpc/grpc-js',
    '@grpc/proto-loader',
    '@nestjs/apollo',
    '@nestjs/common',
    '@nestjs/config',
    '@nestjs/core',
    '@nestjs/cqrs',
    '@nestjs/graphql',
    '@nestjs/microservices',
    '@nestjs/platform-express',
    '@nestjs/typeorm',
    'class-transformer',
    'class-validator',
    'dotenv',
    'graphql',
    'graphql-scalars',
    'pg',
    'postgres',
    'reflect-metadata',
    'rxjs',
    'typeorm',
    'uuid',
  ],
  minify: true,
});
